print("name - VIDHI SHARMA  roll no - 1900300100242")
a=set()
b=set()
print("Enter number of elements for set A :")
n=int(input())
print("Enter number of elements for set B :")
m=int(input())
print("Enter elements for set A : ")
for i in range(1,n+1):
    a.add(input())
print("Enter elements for set B : ")
for i in range(1,m+1):
    b.add(input())
print("Set A :")
print(a)
print("Set B :")
print(b)
print("Intersection :")
print(a.intersection(b))
print("Union :")
print(a.union(b))
print("Set difference :")
print(a.symmetric_difference(b))

